"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Clock3, Home, Heart, Search, ShoppingBag } from "lucide-react";
import Image from "next/image";
import { articles, latest, sellers } from "@/lib/mock-data";
import { Reveal } from "./motion";
import { Badge, LinkButton, SearchField, Select } from "./ui";

export function Dashboard() {
  const [sort, setSort] = useState("orders"); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 650); return () => window.clearTimeout(timer); }, []);
  const sorted = useMemo(() => [...sellers].sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : b.orders - a.orders), [sort]);
  const filtered = latest.filter((item) => `${item.title} ${item.author} ${item.tag}`.toLowerCase().includes(query.toLowerCase()));
  return <main id="works" className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="flex gap-10"><div className="hidden md:block"><aside className="sticky top-24 flex h-[calc(100vh-7rem)] w-56 flex-col"><div className="mb-8 text-xs font-semibold uppercase tracking-[.18em] text-muted">Workspace</div><nav className="space-y-1"><a href="#home" className="flex items-center gap-3 rounded-2xl bg-accent/10 px-4 py-3 text-sm font-medium text-accent">⌂ <span>Home</span></a>{["Cart", "Coupons", "Favorite Items", "Settings"].map((item) => <a key={item} href="#" className="flex items-center gap-3 rounded-2xl px-4 py-3 text-sm text-muted transition hover:bg-black/[.04] hover:text-ink dark:hover:bg-white/[.08]">◦ <span>{item}</span></a>)}</nav><div className="mt-auto border-t hairline pt-5 text-[11px] leading-5 text-muted">© 2024 Lumina<br />Privacy Policy · Terms</div></aside></div><div className="min-w-0 flex-1 space-y-20">
    {loading ? <section aria-label="Loading dashboard" className="space-y-12"><div className="h-10 w-48 animate-pulse rounded-xl bg-black/[.06] dark:bg-white/[.1]" /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Array.from({ length: 8 }).map((_, i) => <div key={i} className="h-40 animate-pulse rounded-3xl bg-black/[.05] dark:bg-white/[.08]" />)}</div><div className="h-10 w-48 animate-pulse rounded-xl bg-black/[.06] dark:bg-white/[.1]" /><div className="grid gap-3 sm:grid-cols-2"><div className="h-52 animate-pulse rounded-3xl bg-black/[.05] dark:bg-white/[.08]" /><div className="h-52 animate-pulse rounded-3xl bg-black/[.05] dark:bg-white/[.08]" /></div></section> : <><Reveal><section aria-labelledby="sellers-title"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.18em] text-accent">People to watch</p><h2 id="sellers-title" className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Top sellers</h2></div><Select value={sort} onChange={setSort} /></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{sorted.map((seller, i) => <div key={seller.id} className="group rounded-3xl border hairline bg-white/50 p-4 transition duration-300 hover:-translate-y-1 hover:shadow-soft dark:bg-white/[.04]"><div className={`relative mb-7 size-11 overflow-hidden rounded-2xl bg-gradient-to-br ${seller.color} shadow-sm`}><Image src={seller.image} alt={`${seller.name} profile`} fill sizes="44px" className="object-cover transition duration-500 group-hover:scale-110" /></div><p className="truncate text-sm font-medium">{seller.name}</p><p className="mt-1 text-xs text-muted">{seller.orders} orders</p><div className="mt-3 h-1 overflow-hidden rounded-full bg-black/[.06] dark:bg-white/[.1]"><div className="h-full rounded-full bg-accent/70" style={{ width: `${Math.max(28, 100 - i * 9)}%` }} /></div></div>)}</div></section></Reveal>
      <Reveal><section aria-labelledby="articles-title"><div className="mb-6 flex items-end justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.18em] text-accent">Curated for you</p><h2 id="articles-title" className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Top articles</h2></div><LinkButton>View all</LinkButton></div><div className="grid gap-3 sm:grid-cols-2">{articles.map((article) => <article key={article.id} className="group relative min-h-52 overflow-hidden rounded-3xl p-6 text-white transition duration-500 hover:-translate-y-1 hover:shadow-soft"><Image src={article.image} alt="" fill sizes="(max-width: 640px) 100vw, 50vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-black/10 to-transparent" /><span className="relative grid size-10 place-items-center rounded-2xl bg-white/75 text-xl text-ink">{article.icon}</span><div className="absolute bottom-5 left-6 right-6"><div className="mb-2 flex items-center gap-2 text-[11px] font-medium uppercase tracking-wider text-white/80"><span>{article.category}</span><span>·</span><span>{article.readTime}</span></div><h3 className="max-w-[240px] text-xl font-semibold leading-tight tracking-[-.03em]">{article.title}</h3></div><ArrowUpRight className="absolute right-5 top-5 text-white/80 transition group-hover:translate-x-1 group-hover:-translate-y-1" size={19} /></article>)}</div></section></Reveal>
      <Reveal><section aria-labelledby="latest-title"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.18em] text-accent">Freshly published</p><h2 id="latest-title" className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Latest</h2></div><div className="flex w-full gap-2 sm:max-w-sm"><SearchField value={query} onChange={setQuery} onClear={() => setQuery("")} /><button aria-label="Search" className="grid size-11 shrink-0 place-items-center rounded-full bg-accent text-white transition hover:bg-[#0077ed]"><ArrowUpRight size={17} /></button></div></div>{filtered.length === 0 ? <div className="rounded-3xl border hairline py-20 text-center text-sm text-muted">No results for “{query}”</div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <article key={item.id} className="group overflow-hidden rounded-3xl border hairline bg-white/50 transition duration-300 hover:-translate-y-1 hover:shadow-soft dark:bg-white/[.04]"><div className={`relative h-40 overflow-hidden bg-gradient-to-br ${item.gradient}`}><Image src={item.image} alt="" fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/25 to-transparent" /><div className="absolute bottom-4 left-5"><Badge className="bg-white/85 text-ink">{item.tag}</Badge></div></div><div className="p-5"><div className="mb-3 flex items-center gap-2 text-xs text-muted"><Clock3 size={13} /> {item.date}</div><h3 className="text-base font-semibold leading-snug tracking-[-.02em]">{item.title}</h3><p className="mt-3 text-sm text-muted">By {item.author}</p></div></article>)}</div>}</section></Reveal>
    </>}</div></div><nav aria-label="Mobile navigation" className="fixed inset-x-4 bottom-4 z-40 flex justify-around rounded-3xl border hairline bg-[color:var(--canvas)]/85 p-2 shadow-soft backdrop-blur-xl md:hidden"><a href="#home" aria-label="Home" className="grid size-11 place-items-center rounded-2xl bg-accent/10 text-accent"><Home size={18} /></a><a href="#works" aria-label="Cart" className="grid size-11 place-items-center rounded-2xl text-muted"><ShoppingBag size={18} /></a><a href="#works" aria-label="Search" className="grid size-11 place-items-center rounded-2xl text-muted"><Search size={18} /></a><a href="#works" aria-label="Favorites" className="grid size-11 place-items-center rounded-2xl text-muted"><Heart size={18} /></a></nav></main>;
}
