"use client";
import { ChevronDown, ChevronRight, Search, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { useState } from "react";

export function Button({ className, variant = "primary", children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "ghost" | "soft" }) {
  return <button className={cn("inline-flex items-center justify-center gap-2 rounded-full px-5 py-2.5 text-sm font-medium transition duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50", variant === "primary" && "bg-accent text-white shadow-[0_8px_24px_rgba(0,113,227,.22)] hover:-translate-y-0.5 hover:bg-[#0077ed]", variant === "ghost" && "text-accent hover:bg-blue-50 dark:hover:bg-blue-950/40", variant === "soft" && "bg-black/[.04] text-ink hover:bg-black/[.08] dark:bg-white/[.08] dark:hover:bg-white/[.13]", className)} {...props}>{children}</button>;
}
export function Badge({ children, className }: { children: React.ReactNode; className?: string }) { return <span className={cn("rounded-full bg-black/[.045] px-2.5 py-1 text-[11px] font-medium text-muted dark:bg-white/[.08]", className)}>{children}</span>; }
export function Select({ value, onChange }: { value: string; onChange: (v: string) => void }) { return <label className="relative inline-flex items-center"><select aria-label="Filter sellers" value={value} onChange={(e) => onChange(e.target.value)} className="appearance-none rounded-full bg-black/[.04] py-2 pl-4 pr-9 text-xs font-medium text-ink outline-none transition hover:bg-black/[.08] dark:bg-white/[.08] dark:hover:bg-white/[.13]"><option value="orders">Most orders</option><option value="name">Name A–Z</option></select><ChevronDown size={14} className="pointer-events-none absolute right-3 text-muted" /></label>; }
export function SearchField({ value, onChange, onClear }: { value: string; onChange: (v: string) => void; onClear: () => void }) { return <div className="relative flex-1"><Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-muted" /><input value={value} onChange={(e) => onChange(e.target.value)} placeholder="Search latest stories" aria-label="Search latest stories" className="h-11 w-full rounded-full border hairline bg-transparent pl-11 pr-10 text-sm outline-none transition placeholder:text-muted focus:border-accent focus:ring-2 focus:ring-accent/20" />{value && <button aria-label="Clear search" onClick={onClear} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-full p-1 text-muted hover:bg-black/5"><X size={15} /></button>}</div>; }
export function LinkButton({ children }: { children: React.ReactNode }) { return <button className="group inline-flex items-center gap-1 text-sm font-medium text-accent transition hover:gap-2">{children}<ChevronRight size={15} /></button>; }
